# Generated by Django 2.1.3 on 2018-11-09 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='OCDE_area',
            new_name='ocde_area',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='OCDE_subarea',
            new_name='ocde_subarea',
        ),
    ]
