# Generated by Django 2.1.3 on 2018-11-09 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizacion', '0002_auto_20181109_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titulados',
            old_name='OECD_area',
            new_name='oecd_area',
        ),
        migrations.RenameField(
            model_name='titulados',
            old_name='OECD_subarea',
            new_name='oecd_subarea',
        ),
    ]
