# Generated by Django 2.1.3 on 2018-11-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizacion', '0003_auto_20181109_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulados',
            name='modality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
